version: '3.8'
services:
  pet-app:
    image: "${APP_IMAGE}"   # find the latest image on dockerhub repo   
    env_file: .envapp 
    deploy: 
      replicas: 5  
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s   
    networks:
      - balancing
      - mysql-net
    depends_on:
      mysqldb:
        condition: service_healthy   


  balancer:
    image: nginx:stable-alpine
    volumes: 
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs:/var/log/nginx
    ports:
      - "90:80"
    depends_on:
      - pet-app
    networks:
      - balancing


  mysqldb:
    image: mysql:latest
    env_file: .envdb
    ports:
      -  '3306'
    volumes:
      -  mysql-vol:/var/lib/mysql
    networks:
      -  mysql-net
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h", "localhost"]
      interval: 1m
      timeout: 10s
      retries: 3

volumes:
  mysql-vol:

networks: 
  mysql-net:
  balancing:
