---
- hosts: web-server
  remote_user: azureuser
  become: yes   
  vars:
    image_name: "{{ image_name }}"   
  tasks: 
    - name: Set the Docker image as an environment variable
      shell: |
        echo "export APP_IMAGE={{ image_name }}" >> /etc/profile.d/app_env.sh
      


    - name: Copy multiple files to the server
      copy:
        src: "../docker/{{ item }}"
        dest: "/home/azureuser/{{ item }}"
      loop:
        - dockercompose.yaml
        - .envapp
        - .envdb
        - default.conf


    - name: stop the application using Docker Compose
      shell:
        "APP_IMAGE={{ image_name }} docker-compose -f /home/ec2-user/dockercompose.yaml down --remove-orphans "
    

    - name: start the application using Docker Compose
      shell:
        "APP_IMAGE={{ image_name }} docker-compose -f /home/ec2-user/dockercompose.yaml up -d"

    - name: Check if the application is running
      wait_for:
        port: 90
        delay: 10
        timeout: 60
