---
- hosts: web-server
  remote_user: ec2-user
  become: yes    
  tasks: 

    - name: Copy dockercompose.yaml to the server
      copy:
        src: ../docker/dockercompose.yaml 
        dest: /home/ec2-user/dockercompose.yaml


    - name: stop the application using Docker Compose
      shell:
        " docker-compose -f /home/ec2-user/dockercompose.yaml down --remove-orphans "
    

    - name: start the application using Docker Compose
      shell:
        " docker-compose -f /home/ec2-user/dockercompose.yaml up -d"

    - name: Check if the application is running
      wait_for:
        port: 90
        delay: 10
        timeout: 60
